export {
  type CompileReport,
  compileStructure,
  DOOR_DEMAND,
  roofAt,
  Structure,
  StructureState,
  swingDoors,
} from './compile'
export {
  CHANNELS,
  CUTOUT_KINDS,
  Cutout,
  DOOR_STATES,
  DoorLeaf,
  Floor,
  HINGES,
  Level,
  OPENING_KINDS,
  Opening,
  Roof,
  StructureChunk,
  StructureSettings,
  type StructureSettingsValue,
  SWINGS,
  WALL_SHAPES,
  Wall,
  WindowPane,
} from './components'
export {
  arcOf,
  type Centerline,
  CURVE_TOLERANCE,
  type CurveInput,
  pointAt,
  quadraticToCubic,
  sampleWall,
  type WallCurve,
} from './curve'
export {
  ClipScratch,
  chunkKey,
  chunkX,
  chunkZ,
  emitFloor,
  emitWall,
  type FloorShape,
  floorChunks,
  floorShape,
  insideRing,
  MeshBuilder,
  type OpeningShape,
  type Piece,
  ringInside,
  ringShape,
  ringsOverlap,
  type SlabFrame,
  type SlabOptions,
  slabY,
  type WallShape,
  wallChunks,
  wallLength,
  wallPieces,
} from './geometry'
export { structureMethods, structurePlugin } from './plugin'
