/**
 * The label font for gizmos: printable ASCII from Inter Regular at 13 px (SIL Open Font License
 * 1.1, © The Inter Project Authors), rasterized into a 192×96 atlas of 12×16 cells, 16 per row,
 * 4 bits of coverage per texel. Built in so labels work in every project and headless, with no font
 * asset to load.
 */
export const LABEL_FONT = {
  width: 192,
  height: 96,
  cellWidth: 12,
  cellHeight: 16,
  columns: 16,
  /** Pixels from the cell top to the baseline. */
  baseline: 12,
  /** Advance in pixels of each character from ' ' (32) to '~' (126). */
  advances: [
    3.5, 3.5, 6, 8, 8.5, 13, 8.5, 4, 4.5, 4.5, 6.5, 8.5, 3.5, 6, 3.5, 4.5, 8, 5.5, 8, 8, 8.5, 8, 8,
    7.5, 8, 8, 3.5, 4, 8.5, 8.5, 8.5, 6.5, 12.5, 9, 8.5, 9.5, 9.5, 8, 7.5, 9.5, 9.5, 3.5, 7.5, 8.5,
    7.5, 11.5, 10, 10, 8.5, 10, 8.5, 8.5, 8.5, 9.5, 9, 13, 9, 9, 8, 4.5, 4.5, 4.5, 6, 6, 4, 7.5, 8,
    7.5, 8, 7.5, 5, 8, 7.5, 3, 3, 7, 3, 11.5, 7.5, 8, 8, 8, 5, 7, 4.5, 7.5, 7.5, 10.5, 7, 7.5, 7,
    5.5, 4.5, 5.5, 8.5,
  ],
} as const

const PACKED =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2AAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAAAAGRGAAAAAAJgCAAA' +
  'AAObYQAAAAeDAAGAAASHEAAAAGQAAAAAAATQAAAAAuEAAAAAAAJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC1AAAA' +
  'AAAAAAAAALgAAAAAAJiLAAAAAAeAHQAAAG6rvBAAAGpdEAiAAE6KsAAAAJgAAAAAAApwAAAAAKcAAAAAAFSxQAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAALgAAAAAAIiLAAAAAAhgSwAAAOVIDHAAAIgLQEwAAIgC8AAAAIgAAAAA' +
  'AB8gAAAAAGwAAAAAAazdYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWwAAAAAAAAAAAAALgAAAAAAIiIAAAAAr7LzbAA' +
  'AOVIAAAAAHouEdIAAG0ZsAAAAIgAAAAAAF0AAAAAAC8QAAAAAEz4EAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiAAAAA' +
  'AAAAAAAAALgAAAAAACISAAAAAA4AhgAAAG+5EAAAAAi1CnAAAAvrEAAAACIAAAAAAIsAAAAAAA9AAAAAAqa3gAAAAABLAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAA0wAAAAAAAAAAAAALgAAAAAAAAAAAAAAA4AtAAAAAOf6AAAAAAAWwAwAF7nAiAAAAAAAAAA' +
  'AIgAAAAAAAtAAAAAAAOAAAAAADR8RBAAAAAAAAAAAIiIAAAAAAAAAAAAAC4AAAAAAAAAAAAAALgAAAAAAAAAAAAABp2I6EAA' +
  'AABITWAAAAAB0h28AuY+WIAAAAAAAAAAAIgAAAAAAAtAAAAAAAAAAAAAAIvOuzAAAAAAAAAAAIiIAAAAAAAAAAAAAGoAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAABruI2CAAAoBICIAAAAALUGgLBMAF7WAAAAAAAAAAAIoAAAAAAA5AAAAAAAAAAAAAAABLAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAJYAAAAAAAAAAAAAAHUAAAAAAAAAAAAAAIcEsAAAAehITmAAAAB6AGgLAvMBvhAAAAAAAAAA' +
  'AF0AAAAAAC8QAAAAAAAAAAAAAABLAAAAADIAAAAAAAAAAAAAAIUAAAAAAOIAAAAAAAAAAAAAAOoAAAAAAAAAAAAAALQHgAAA' +
  'AD3/6AAAAALRAB28AG7vmbAAAAAAAAAAAB8wAAAAAHwAAAAAAAAAAAAAAAATAAAAALcAAAAAAAAAAAAAAOoAAAAAA9AAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAAAAAAABAAAAQAAAAAAAAAAAAAAmAAAAAAMYAAAAAAAAAAAAAAAAAAAAA' +
  'AOMAAAAAAAAAAAAAAAAAAAAAB5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAKgAAAAAqAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAABjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAKIQAAAAAWCAAAAAASIQAAAAASIQAAAAAACggAAACiIhgAAAAKIYAAABIiIhgAAAASIQAAAAASIMAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAABiGAAAAAD6I5gAAAY30AAAAAG6I5QAAAG6I5gAAAAAL9AAAAH2IhgAAAC6Y2AAABIiIywAA' +
  'AG6I5gAAAI6I5QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeqNgAAAALgATgAACKH0AAAAAOUAawAAAOUAbQAA' +
  'AABctAAAAIkAAAAAAKgALyAAAAAB5gAAAMYAbQAAAfQAbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AE8AAA' +
  'AfIADkAAAgD0AAAAAEEAawAAAAAAbQAAAAHktAAAAKgjAAAAAPEUAAAAAAAIsAAAAMYAXAAABPAADzAAAIYAAAAAAIgAAAAA' +
  'AAAAbQAAAAAAAAAAAIkgAAAAAAAF4AAABPAAC3AAAAD0AAAAAAABxwAAAABI1QAAAAiAtAAAAL7v0wAAA/f+4wAAAAAeQAAA' +
  'AF2I1QAAAvIAT0AAAMgAAAAAAIsAAAAAAABM1gAAAEiIiCAAACn5IAAAAABeYAAABPAAC4AAAAD0AAAAAAAJsAAAAAC7xQAA' +
  'AE4QtAAAADMAmwAABPoQjhAAAACLAAAAAF271gAAAI1n3UAAAAAAAAAAAAAAAAAAAEvWAAAAAEiIiCAAAAAo6SAAAATkAAAA' +
  'A/AADFAAAAD0AAAAAACcEAAAAAAATyAAANUAtAAAAAAALxAABPIAD0AAAAHkAAAAAeQATxAAAAe5LjAAAAAAAAAAAAAAAAAA' +
  'AN5AAAAAAAAAAAAAAAAAf3AAAAiQAAAAAOUAHzAAAAD0AAAAAAjBAAAAAoAAD0AABP///7AAAIIALwAAAPMAD0AAAAiwAAAA' +
  'BPAAD0AAAYEALgAAAAAAAAAAAAAAAAAAAAbbQAAAAGu7uzAAAAGNtAAAAAIgAAAAAIwQmwAAAAD0AAAAAG0QAAAAAegAfhAA' +
  'AAAAtAAAALkBmwAAAJoQnQAAAB5AAAAAAecAfhAAANgByAAAAIUAAAAAADIAAAAAAAAG2wAAACRERBAAAF60AAAAAAVQAAAA' +
  'ABr/sQAAAAD0AAAAAP///wAAAD3/0wAAAAAAtAAAADv/sQAAABv/0wAAAIsAAAAAAD3/1AAAAD3/gAAAAOoAAAAAALcAAAAA' +
  'AAAABgAAAAAAAAAAAFQAAAAAAAqgAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAOMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAoIAAAAGiIYAAAAABohQAAAGiIUAAAAGiIiAAAAGiIhgAAAABohQAA' +
  'AGIAAGQAAGIAAAAAAAAAggAAAGIAA4EAAGIAAAAAAGgAAAKEAGUAAEYAAABYhQAAAACN29xQAACegAAAALmI3BAAABvYjbAA' +
  'ALmJzTAAALmIiAAAALmIhgAAABzYjqAAALQAALgAALQAAAAAAAAA9AAAALQAPmAAALQAAAAAAL9AAAj4AL8wAIsAABvYjrAA' +
  'AAyiAATHAADn0AAAALQADVAAAIwQAdcAALQACOEAALQAAAAAALQAAAAAAIwQAdgAALQAALgAALQAAAAAAAAA9AAAALQC6QAA' +
  'ALQAAAAAALyQAA2oALvAAIsAAIwQAcgAAIsARCMdAAXQ5AAAALQADGAAAOQAAEYAALQAANYAALQAAAAAALQAAAAAAPQAAEYA' +
  'ALQAALgAALQAAAAAAAAA9AAAALQckAAAALQAAAAAALfhAE2IALTXAIsAAOQAAF4AAOMKudsHAAqAmQAAALdEqxAABPAAAAAA' +
  'ALQAAIgAALdEQgAAALdEQgAABPAAAAAAALdERMgAALQAAAAAAAAA9AAAALXLAAAAALQAAAAAALTWAJiIALROIIsABPAAAA8g' +
  'A/BbAFsEAB8wPgAAALy7yhAABPAAAAAAALQAAIgAALy7tgAAAL//+AAABPAAi7sAALy7u+gAALQAAAAAAAAA9AAAALy/MAAA' +
  'ALQAAAAAALR8AfKIALQKsIsABPAAAA9ABLCIAEsEAG+7v2AAALQACpAAAvEAAAAAALQAAKgAALQAAAAAALQAAAAAAvEANH0A' +
  'ALQAALgAALQAAAAAATAA9AAAALkIwQAAALQAAAAAALQfNrCIALQB5YsAAvEAAC8ABNB5AFsEAMhESaAAALQACLAAANgAAIoA' +
  'ALQAAvMAALQAAAAAALQAAAAAANgAAIoAALQAALgAALQAAAAABMAA9AAAALQAyAAAALQAAAAAALQJjGCIALQAbosAANgAAIsA' +
  'APEtVM0aAvIAAvIAALQAPIAAAF9wB/MAALQBXZAAALQAAAAAALQAAAAAAF9wB/QAALQAALgAALQAAAAAAvQG8QAAALQAPlAA' +
  'ALQAAAAAALQEzhCIALQAC+sAAF9wF/QAAKgDqzi4B8AAAMcAAL//6RAAAAXf/VAAAL//yAAAAL///wAAALQAAAAAAAXf/VAA' +
  'ALQAALgAALQAAAAAAG7+YAAAALQAB+EAAL//+wAAALQA2QCIALQAAusAAAXf/VAAAD5gAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAPciIowAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGiIUAAAAABYhQAAAGiIUAAAAAOIYQAA' +
  'BIiIiGAAAGIAAGQABWAAAGQABVAAKBAAAoEAAYEABHAAAIMAAoiIiCAAAI/wAAAACXAAAAAABP9AAAAAAAIwAAAAAAAAAAAA' +
  'ALmI3BAAABvYjrAAALmI3BAAAG6IvBAABIi9iGAAALQAALgABeAAAOUABsAAj1AAALgACqAAAuUACNEAAoiIjzAAAIgAAAAA' +
  'BaAAAAAAAAtAAAAAAA3hAAAAAAAAAAAAALQADXAAAIwQAcgAALQADHAAAOUADXAAAACLAAAAALQAALgAAOUABeAAAvEAy5AE' +
  'AC5QfhAAAH0QLkAAAAAAqAAAAIgAAAAAAfAAAAAAAAtAAAAAAGuYAAAAAAAAAAAAALQACIAAAOQAAF4AALQACIAAAOUAAAAA' +
  'AACLAAAAALQAALgAAJkACoAAANUB9dAIAAfj5AAAAAyAugAAAAAH0QAAAIgAAAAAAMQAAAAAAAtAAAAAANQuEAAAAAAAAAAA' +
  'ALQADHAABPAAAA8gALQAHXAAAG+VEAAAAACLAAAAALQAALgAAD8QHzAAAJgFwPIMAACugAAAAAT24QAAAAAuQAAAAIgAAAAA' +
  'AIgAAAAAAAtAAAAABJAIUAAAAAAAAAAAALmIvhAABPAAAA9AALy76xAAAAON6AAAAACLAAAAALQAALgAAA1gbQAAAFwIgLYf' +
  'AACPcAAAAACPcAAAAAC4AAAAAIgAAAAAAEwAAAAAAAtAAAAAAAAAAAAAAAAAAAAAALmIcQAAAvEAAC8AALdG4gAAAAAATWAA' +
  'AACLAAAAALQAALgAAAegpwAAAB8tQHldAAP24gAAAABPAAAAAAfRAAAAAIgAAAAAAA8QAAAAAAtAAAAAAAAAAAAAAAAAAAAA' +
  'ALQAAAAAANgC44sAALQAuQAAAoAACIAAAACLAAAAALgAAMcAAALy8gAAAAxvAD2IAB2AiwAAAABPAAAAAC5AAAAAAIgAAAAA' +
  'AApQAAAAAAtAAAAAAAAAAAAAAAAAAAAAALQAAAAAAF9wXvQAALQATyAAAegATmAAAACLAAAAAG5AGOIAAAC7sAAAAAjKAA7V' +
  'AIsAHYAAAABPAAAAALgAAAAAAIgAAAAAAAeQAAAAAAtAAAAAAAAAAAAAAAAAAAAAALQAAAAAAAXf/rAAALQACrAAAD3/6AAA' +
  'AACLAAAAAAjv/TAAAABvYAAAAAT3AAnxBeIABPMAAABPAAAABP///4AAAIgAAAAAAAPQAAAAAAtAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAMcAAAAAAAAAAAAjAAAAAAAAAAAAAAADIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIlAAAAA' +
  'AADiAAAAAUxAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAGuwAAAAAABjAAAAA7swAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'ALYAAAAAAAAAAAAAAIIAAAAAAAAAAAAAAAAAKAAAAAAAAAAAABnmAAAAAAAAAAAAAIIAAAAAAbIAAAAAArIAAAAAAIIAAAAA' +
  'AIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD0AAAAAAAAAAAAAAPQAAAAAAAAAAAAAAAAATwAAAAAAAAAAAH1BAAAAAAAAAAAA' +
  'APQAAAAAAaIAAAAAAaIAAAAAAPQAAAAAAPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAPQUAAAAAAAyAAAA' +
  'AABBTwAAAAAyAAAAAIsAAAAAAABBAAAAAPQUAAAAAAAAAAAAAAAAAAAAAPQAAAAAAPQAAAAAAAAjACMAAAAUAAAAAAAyAAAA' +
  'AAAAAAAAAH++gAAAAPnt0wAAAD3esQAAAD7ejwAAAD3esQAAC//0AAAAAD7enwAAAPne0gAAAPQAAAAAAPQAAAAAAPQF4wAA' +
  'APQAAAAAAPbOic7AAPbe0gAAAD3esQAAAAAAAAAAAaMB4wAAAPoAfQAAANcAqAAAAOcAvwAAANYAqQAAAIsAAAAAAOcArwAA' +
  'APkAuAAAAPQAAAAAAPQAAAAAAPQ9MAAAAPQAAAAAAPYB+AHUAPgAuAAAANcAqgAAAAAAAAAAAAAk1AAAAPQAD0AABOAAAAAA' +
  'BOAAXwAABOREjQAAAIsAAAAABOAATwAAAPQAiwAAAPQAAAAAAPQAAAAAAPfTAAAAAPQAAAAAAPQA9AC4APQAiwAABOAALwAA' +
  'AAAAAAAAAJ/K1AAAAPQADEAABLAAAAAABLAATwAABOu7uwAAAIsAAAAABLAATwAAAPQAiwAAAPQAAAAAAPQAAAAAAP7zAAAA' +
  'APQAAAAAAPQA9AC4APQAiwAABLAADyAAAAAAAAAABtEAxAAAAPUADzAABOAAEAAABOAAXwAABNAAAAAAAIsAAAAABPEAXwAA' +
  'APQAiwAAAPQAAAAAAPQAAAAAAPV+EAAAAPQAAAAAAPQA9AC4APQAiwAABOAALwAAAAAAAAAABtEF9AAAAPsQjQAAANgAqQAA' +
  'ANcBzwAAANgAmAAAAIsAAAAAAMlFvwAAAPQAiwAAAPQAAAAAAPQAAAAAAPQKsAAAAPQAAAAAAPQA9AC4APQAiwAAANgAqQAA' +
  'AAAAAAAAAb7ZtAAAAPXu0wAAAD3vsQAAAD3ujwAAAD3uwwAAAIsAAAAAABnafwAAAPQAiwAAAPQAAAAAAPQAAAAAAPQByAAA' +
  'APQAAAAAAPQA9AC4APQAiwAAAD3vsQAAAAAAAAAAAAIgAAAAAAATAAAAAAAhAAAAAAAwAAAAAAAiAAAAAAAAAAAAABAATwAA' +
  'AAAAAAAAAAAAAAAAAPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAMlEyQAAAAAAAAAAAAAAAAAAKOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm7gQAAAAAAAAAAAAAAAAAAOTAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEsAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AEsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAPbAAAAAEsAAAAABPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AIMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmAAAAAAEsAAAAAAB4gAAAAAAAAAAAAAAAAAAAA' +
  'AAAUAAAAAABBAAAAAAAiAAAAAAFBAAAAALQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtAAAAA' +
  'AEsAAAAAAAtAAAAAAAAAAAAAAAAAAAAAAPbt0wAAAD7ejwAAAPj4AAAAAG++YAAAC/+wAAAAAPQAiwAAB8AAiwAABsAH8gPx' +
  'AeQC8wAAB8AAiwAAAP//9AAAAAtAAAAAAEsAAAAAAAtAAAAAAAAAAAAAAAAAAAAAAPoAfQAAAOcAvwAAAPkAAAAAAPMDoAAA' +
  'ALQAAAAAAPQAiwAAAfIA1gAAAfIK1gegAF0bgAAAAfIA1gAAAAAJsAAAAAxAAAAAAEsAAAAAAAtQAAAAAAAAAAAAAAAAAAAA' +
  'APQAD0AABOAAXwAAAPQAAAAAAOggAAAAALQAAAAAAPQAiwAAAJgD4AAAAMYPaQtgAArMAAAAAJgD4AAAAABtEAAAAMoQAAAA' +
  'AEsAAAAAAATIAAAAAG7UBmAAAAAAAAAAAPQADEAABLAATwAAAPQAAAAAADr9YAAAALQAAAAAAPQAiwAAAF0IkAAAAHlLLg8g' +
  'AAT2AAAAAF0JkAAAAAPjAAAAAI4gAAAAAEsAAAAAAAjGAAAAANZOjkAAAAAAAAAAAPUADzAABOAAXwAAAPQAAAAAAAAF8gAA' +
  'ALQAAAAAAPQAiwAAAA0+MAAAAC6HDHwAAByNEAAAAA0+MAAAAB1wAAAAAAtAAAAAAEsAAAAAAAtAAAAAAEAChAAAAAAAAAAA' +
  'APsQjQAAANcBzwAAAPQAAAAAAtED8gAAALYAAAAAANgC2wAAAAi8AAAAAA3TCNgAAIsJoAAAAAjMAAAAAKoAAAAAAAtAAAAA' +
  'AEsAAAAAAAtAAAAAAAAAAAAAAAAAAAAAAPju0wAAAD3ujwAAAPQAAAAAAI/OcAAAAG/QAAAAAD79mwAAAAL3AAAAAAjQBPMA' +
  'BOIB5QAAAAL3AAAABP//+AAAAAtQAAAAAEsAAAAAAAtAAAAAAAAAAAAAAAAAAAAAAPQTAAAAAAAwTwAAAAAAAAAAAABAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALxAAAAAAAAAAAAAAijAAAAAEsAAAAAAV8QAAAAAAAAAAAAAAAAAAAA' +
  'APQAAAAAAAAATwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEqQAAAAAAAAAAAAAAGYAAAA' +
  'AEsAAAAAA7UAAAAAAAAAAAAAAAAAAAAAALMAAAAAAAAAOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAALgQAAAAAAAAAAAAAAAAAAAAAEsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'

let atlas: Uint8Array | undefined

/** The atlas as one byte of coverage per texel (r8unorm), unpacked on first use. */
export function labelAtlas(): Uint8Array {
  if (atlas) return atlas
  const bytes = Uint8Array.from(atob(PACKED), (c) => c.charCodeAt(0))
  atlas = new Uint8Array(bytes.length * 2)
  for (let i = 0; i < bytes.length; i++) {
    atlas[i * 2] = (bytes[i]! >> 4) * 17
    atlas[i * 2 + 1] = (bytes[i]! & 15) * 17
  }
  return atlas
}

/** Width in pixels of a label's text ('?' stands in for characters outside ASCII). */
export function labelWidth(text: string): number {
  let w = 0
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i)
    w += LABEL_FONT.advances[c >= 32 && c < 127 ? c - 32 : 31]!
  }
  return w
}
