import {
  allAssetSchemas,
  allDataTypes,
  allImporters,
  type DataType,
  type ImporterDef,
} from '@shard/assets'
import { allComponents, type ComponentDef, type JsonSchema } from '@shard/core'
import { prefabJsonSchema, sceneJsonSchema } from '@shard/scene'
import { BUILTIN_PLUGINS, type ManifestValue, manifestJsonSchema } from './manifest'

export const GENERATED_START = '<!-- shard:generated -->'
export const GENERATED_END = '<!-- /shard:generated -->'

export interface ErrorCode {
  code: string
  hint?: string
  /** Package or file it comes from. */
  source: string
}

function fieldRow(name: string, schema: JsonSchema): string {
  const type = describeType(schema)
  const def = schema.default === undefined ? '' : `\`${JSON.stringify(schema.default)}\``
  const range = [
    schema.minimum !== undefined ? `≥ ${schema.minimum}` : '',
    schema.maximum !== undefined ? `≤ ${schema.maximum}` : '',
    schema['x-unit'] ? `${schema['x-unit']}` : '',
  ]
    .filter(Boolean)
    .join(', ')
  const presets = schema['x-presets']
    ? ` Presets: ${Object.keys(schema['x-presets'] as object).join(', ')}.`
    : ''
  const description = `${(schema.description as string | undefined) ?? ''}${presets}`.replace(
    /\|/g,
    '\\|',
  )
  return `| \`${name}\` | ${type} | ${def} | ${range} | ${description} |`
}

function describeType(schema: JsonSchema): string {
  if (schema.anyOf) return (schema.anyOf as JsonSchema[]).map(describeType).join(' or ')
  if (schema.enum) return (schema.enum as string[]).map((v) => `\`"${v}"\``).join(' \\| ')
  if (schema.type === 'array') {
    const n =
      schema.minItems === schema.maxItems && schema.minItems !== undefined
        ? `${schema.minItems}`
        : ''
    return `${describeType((schema.items as JsonSchema) ?? {})}[${n}]`
  }
  if (schema.type === 'object' && schema.properties && (schema.properties as JsonSchema).guid)
    return schema['x-asset-type'] ? `${schema['x-asset-type']} ref` : 'asset ref'
  return (schema.type as string | undefined) ?? 'any'
}

/** A readable catalog of components: the same facts as the JSON Schemas, for agents to skim. */
export function renderComponentCatalog(defs: readonly ComponentDef[] = allComponents()): string {
  const visible = defs.filter((d) => !d.name.startsWith('test/'))
  const lines = [
    '# Components',
    '',
    'Generated by `shard docs` from the registry. Use these names as keys under `components` in scene files.',
    '',
  ]
  for (const def of visible) {
    lines.push(`## \`${def.name}\``, '')
    if (def.description) lines.push(def.description, '')
    if (!def.serializable) lines.push('_Computed by the engine; never written in scene files._', '')
    if (def.requires.length > 0)
      lines.push(`Brings along: ${def.requires.map((r) => `\`${r.name}\``).join(', ')}.`, '')
    const props = (def.jsonSchema().properties ?? {}) as Record<string, JsonSchema>
    if (Object.keys(props).length === 0) {
      lines.push('Tag (no fields).', '')
      continue
    }
    lines.push('| Field | Type | Default | Range | Description |', '|---|---|---|---|---|')
    for (const [name, schema] of Object.entries(props)) lines.push(fieldRow(name, schema))
    if (def.name === 'core/Transform') {
      lines.push(
        '| `rotationEuler` | number[3] | | degrees | Scene files only: rotation as X, then Y, then Z degrees. |',
      )
    }
    lines.push('')
  }
  return lines.join('\n')
}

export function renderErrorCatalog(codes: readonly ErrorCode[]): string {
  const lines = [
    '# Error codes',
    '',
    'Every engine error is a `ShardError` with one of these codes.',
    '',
  ]
  lines.push('| Code | Source | Hint |', '|---|---|---|')
  for (const c of [...codes].sort((a, b) => a.code.localeCompare(b.code))) {
    lines.push(`| \`${c.code}\` | ${c.source} | ${(c.hint ?? '').replace(/\|/g, '\\|')} |`)
  }
  return `${lines.join('\n')}\n`
}

/**
 * Importers: which files they handle, what they produce, and their `.meta` settings. Then the
 * project's own data types: fields, file extension, and schema.
 */
export function renderAssetCatalog(
  importers: readonly ImporterDef[] = allImporters(),
  dataTypes: readonly DataType[] = [],
): string {
  const projectImporters = new Set(dataTypes.map((d) => d.importer.name))
  const visible = importers.filter(
    (i) => !i.name.startsWith('test') && !projectImporters.has(i.name),
  )
  const lines = [
    '# Assets',
    '',
    'Generated by `shard docs`. Files under the asset roots (`assetRoots` in shard.json) are imported',
    'by extension. Each gets a `.meta` next to it with its guid and import settings; commit both.',
    'Reference assets in scenes by path: `{ "path": "materials/hull.material.json" }`, or a',
    'sub-asset with `#`: `{ "path": "assets/ship.glb#Mesh/Hull" }`.',
    '',
  ]
  for (const importer of visible) {
    lines.push(`## \`${importer.name}\``, '')
    lines.push(`Files: ${importer.extensions.map((e) => `\`*${e}\``).join(', ')}`, '')
    const props = (importer.settings.jsonSchema().properties ?? {}) as Record<string, JsonSchema>
    if (Object.keys(props).length === 0) {
      lines.push('No import settings.', '')
      continue
    }
    lines.push('| Setting | Type | Default | Range | Description |', '|---|---|---|---|---|')
    for (const [name, schema] of Object.entries(props)) lines.push(fieldRow(name, schema))
    lines.push('')
  }
  if (dataTypes.length > 0) {
    lines.push(
      '# Project data types',
      '',
      'Defined in `scripts/` with `project.dataAsset`. Write one JSON file per value, anywhere under an',
      'asset root (by convention `data/<kind>/`). A file can start from another of the same type with',
      '`"$extends": { "path": "..." }` and override fields. Reference them from components and other',
      "data types with `t.handle('<type>')`; read them with `world.resource(Type.store).get(ref)`.",
      '',
    )
    for (const type of dataTypes) {
      lines.push(`## \`${type.name}\``, '')
      if (type.description) lines.push(type.description, '')
      lines.push(
        `Files: \`*.${type.extension}.json\` (e.g. \`data/${type.extension}s/<name>.${type.extension}.json\`). ` +
          `Schema: \`.shard/schemas/${type.extension}.schema.json\`.`,
        '',
      )
      const props = (type.jsonSchema().properties ?? {}) as Record<string, JsonSchema>
      if (Object.keys(props).length === 0) {
        lines.push('No fields.', '')
        continue
      }
      lines.push('| Field | Type | Default | Range | Description |', '|---|---|---|---|---|')
      for (const [name, schema] of Object.entries(props)) lines.push(fieldRow(name, schema))
      lines.push('')
    }
  }
  return `${lines.join('\n')}\n`
}

const SKILLS: Record<string, string> = {
  'build-a-scene.md': `# Build or change a scene

1. Read \`.agents/components.md\` for component names and fields.
2. Edit \`scenes/*.scene.json\`. Name every entity; nest with \`children\`. Materials go in \`assets\`
   (\`{ "type": "Material", "value": {...} }\`), meshes can be procedural
   (\`{ "path": "procedural:sphere?radius=2" }\`).
3. Validate: \`shard validate --json\` (or the MCP \`validate_scene\` tool). Fix every error by its \`path\`.
4. Look at it: \`shard screenshot scenes/main.scene.json --out shot.png\` (or MCP \`screenshot\`).
`,
  'add-a-component.md': `# Add a component

In \`scripts/\`, define it on the project so it gets the project namespace:

\`\`\`ts
export const Fuel = project.component('Fuel', {
  liters: t.f32({ default: 100, min: 0, unit: 'L', description: 'Fuel left.' }),
})
\`\`\`

Write a description for every field: it ends up in \`.agents/components.md\`. Run \`shard docs\` after.
`,
  'write-a-system.md': `# Write a system

\`\`\`ts
const burn = defineSystem({
  name: '<project>/burn',
  setup: (world) => ({ q: world.query({ with: [Fuel] }) }),
  run: ({ q }, world) => {
    const dt = world.resource(FixedTime).step
    for (const table of q.tables) {
      const liters = table.column(Fuel, 'liters')
      for (let i = 0; i < table.count; i++) liters[i] = Math.max(0, liters[i]! - dt)
      table.markChanged(Fuel)
    }
  },
})
\`\`\`

Register it in the project's \`build(app)\`: \`app.addSystems(FixedUpdate, burn)\`. Hot loops must not
allocate: walk \`q.tables\` and use columns.
`,
  'write-a-gameplay-test.md': `# Write a gameplay test

\`\`\`ts
import { expect, test } from '@shard/testing'

test('thrust moves the ship', async ({ game }) => {
  await game.load('scenes/main.scene.json')
  game.input.hold('<project>/Controls.thrust')
  await game.step(120)
  expect(game.get('ship', 'core/Transform').translation[2]).toBeLessThan(0)
})
\`\`\`

Run with \`shard test --json\`. Tests are headless, seeded, and fixed-timestep: they pass or fail the
same way every run.
`,
  'iterate-on-a-system.md': `# Change game code and see it run

1. Edit a system or component in \`scripts/\`. The running game (MCP server, \`shard dev\` page)
   rebuilds and hot reloads on save, keeping every entity and resource.
2. Check it took: MCP \`project_status\` (or the note in \`step\`'s result). A failed build or reload
   reports \`source\` as \`scripts/<file>.ts:line:col\`, and the previous code keeps running.
3. \`step\` some frames and \`screenshot\` or \`get_entity\` to see the effect.
4. Run \`typecheck\` (\`shard check --json\`): reloads don't wait for type errors.
5. Changing a component's fields migrates live data: new fields take their defaults, removed ones
   are dropped. To rename a field, bump the component's \`version\` and move the value in \`migrate\`.
`,
  'use-assets.md': `# Use asset files

1. Put files under an asset root (\`assets/\`, \`materials/\`, \`data/\`). \`.agents/assets.md\` lists
   what each extension imports as and its settings.
2. Import: \`shard import --json\` (MCP \`reimport_asset\` with no "asset"). Fix failures by their \`path\`.
3. Reference by path in scenes: \`"material": { "path": "materials/hull.material.json" }\`.
4. Inspect with MCP \`get_asset\` (sub-assets, bounds, dependents, errors); change import settings
   with \`reimport_asset\` and \`{ "settings": {...} }\`.
5. Move or rename with \`shard mv <from> <to>\` (MCP \`move_asset\`), never by hand: it keeps the
   \`.meta\` with the file and rewrites references.
6. Look before you place: MCP \`preview_asset\` renders a texture, a material, or a model.

Models: place a .glb/.gltf with \`"scene/SceneInstance": { "scene": { "path": "assets/ship.glb#Scene" } }\`;
its nodes become children you can address by path (\`ship/Hull\`), changed per placement with
\`overrides\` (see make-a-prefab.md). Reusable entity trees are prefabs (\`prefabs/*.prefab.json\`).

Textures: a texture's \`usage\` setting says what it holds: \`color\` (albedo, emissive; sRGB),
\`data\` (roughness, metallic, occlusion; linear), \`normal\` (tangent-space normal map), \`hdr\`.
New files get a usage from their name (\`*_normal*\`, \`*rough*\`, \`*_orm*\`, \`*.hdr\`). Materials
use textures through slots: \`"baseColorTexture": { "texture": { "path": "assets/rock.png" } }\`
(also metallicRoughnessTexture, normalTexture, occlusionTexture, emissiveTexture).
`,
  'write-a-material.md': `# Write a material

A material type is a schema plus a shader that overrides hooks. Lighting, shadows, and post effects
keep working because the shader only changes the surface.

1. Define it in \`scripts/\`:

   \`\`\`ts
   export const Lava = project.material('Lava', {
     fields: {
       crackColor: t.color({ default: [1, 0.3, 0.05, 1] }),
       crackLuminance: t.f32({ default: 20000, unit: 'cd/m²' }),
       flow: t.vec2({ default: [0.02, 0], description: 'UV scroll per second.' }),
       cracks: t.handle('Texture', { description: 'Crack mask (R).' }),
     },
     shader: 'project::lava',
   })
   \`\`\`

2. Write \`shaders/lava.wesl\`. The generated module \`material::lava\` has the uniform (\`Lava\`)
   and one texture and sampler per texture field (\`Lava_cracks\`, \`Lava_cracks_sampler\`):

   \`\`\`wesl
   import shard::pbr::types::{ VertexOutput, PbrInput };
   import shard::pbr::standard::standard_input;
   import shard::globals::globals;
   import material::lava::{ Lava, Lava_cracks, Lava_cracks_sampler };

   override fn pbr_input(in: VertexOutput) -> PbrInput {
     var p = standard_input(in);
     let uv = in.uv + Lava.flow * globals.time;
     let crack = textureSample(Lava_cracks, Lava_cracks_sampler, uv).r;
     p.emissive += Lava.crackColor.rgb * Lava.crackLuminance * crack;
     return p;
   }
   \`\`\`

   Hooks: \`vertex_position(position, normal, uv) -> vec3f\` (object-space displacement, applied in
   every pass, shadows included), \`pbr_input(in) -> PbrInput\` (the surface), and
   \`fragment_output(color) -> vec4f\` (pre-exposed HDR, before tonemapping). With
   \`extends: 'none'\`, override \`shade(in) -> vec4f\` instead: it returns radiance in cd/m² and
   alpha, and no lighting runs.

3. Use it in a material file: \`{ "type": "<project>/Lava", "crackLuminance": 30000,
   "cracks": { "path": "assets/cracks.png" } }\`. Leaving out \`"type"\` means the standard material.
4. Check it: \`shard validate --json\` (bad fields are reported by path), then MCP \`preview_asset\`
   on the material file. Shader errors appear in \`recent_errors\` as \`shaders/lava.wesl:line:col\`,
   and the last shader that compiled keeps running.
`,
  'make-2d.md': `# Make 2D: sprites, animation, tilemaps

Add \`"sprite"\` to \`plugins\` in \`shard.json\`. 2D uses the same renderer as 3D (HDR, post effects).

1. An atlas. Either drop images in a folder and add \`assets/sprites/hero.atlas-pack.json\`
   (\`{}\` packs \`assets/sprites/hero/*.png\`; regions are the file names), or write
   \`hero.atlas.json\`: \`{ "texture": { "path": "assets/sheet.png" }, "grid": { "columns": 8,
   "rows": 4, "cellWidth": 16, "cellHeight": 16 } }\` (regions \`cell0\`, \`cell1\`, …) and/or
   \`"regions": [{ "name": "idle_0", "rect": [x, y, w, h] }]\`.
2. A sprite: \`"sprite/Sprite": { "atlas": { "path": "assets/sprites/hero.atlas-pack.json" },
   "region": "idle_0", "layer": 1 }\`. No \`size\`: pixels ÷ \`Sprite2dSettings.pixelsPerUnit\` (100).
   Higher \`layer\` draws on top; within a layer, higher z does. \`"space": "screen"\` makes an
   overlay positioned in pixels.
3. Animation: \`walk.clip.json\` = \`{ "atlas": {...}, "frames": [{ "region": "walk_0",
   "duration": 0.1 }, ...], "loop": "loop", "events": [{ "frame": 2, "name": "step" }] }\`, then
   \`"sprite/SpriteAnimation": { "clip": { "path": "assets/walk.clip.json" } }\`. Read events with
   \`world.reader(SpriteAnimationEvent)\`.
4. Tilemaps: \`level.tilemap.json\` layers are base64 u16 tiles (atlas region + 1, 0 empty), and
   \`"sprite/Tilemap": { "atlas": ..., "data": ..., "tileSize": [1, 1] }\`. Edit at runtime with
   \`setTile(world, map, x, y, tile)\`; only that chunk re-uploads.
5. Pixel art: \`"render/PixelPerfect": { "pixelsPerUnit": 16 }\` on an orthographic camera.
6. Check: \`shard validate\`, MCP \`preview_asset\` on the atlas (regions outlined and numbered) or
   the clip, and \`render.describe\` → \`sprites\` (draw calls, sprites per layer, tilemap chunks).
`,
  'show-text.md': `# Show text

Add \`"text"\` to \`plugins\` in \`shard.json\` and put a \`.ttf\` or \`.otf\` under \`assets/\` (import
settings: \`charset\`, \`size\`, \`range\`, \`fallback\` fonts for missing characters).

- In the world: \`"text/Text": { "value": "Scanner 7", "font": { "path": "assets/fonts/Inter.ttf" },
  "size": 0.5, "billboard": true }\`. \`size\` is the em height in meters.
- On screen: \`"text/ScreenText": { "value": "Fuel 82%", "font": ..., "size": 24, "corner":
  "top-right", "position": [-16, 16] }\` (pixels from the corner, y down).
- Style: \`outline: { width: 0.03, color }\`, \`shadow: { offset: [0.05, -0.05], softness: 0.3, color }\`
  (offset 0 with softness is a glow), \`weight\`. Wrap with \`maxWidth\`; \`align\` and \`anchor\` place it.
- Size before placing: MCP \`measure_text\` returns width, height, and lines. \`preview_asset\` on the
  font shows a specimen. Missing characters: \`render.describe\` → \`text.missing\`.
`,
  'add-physics.md': `# Add physics

Add \`"physics3d"\` (or \`"physics2d"\` for a 2D game, never both) to \`plugins\` in \`shard.json\`.
Bodies and colliders are components, so scenes, prefabs, and \`patch_entity\` create and change them:

\`\`\`json
{ "name": "crate", "components": {
  "core/Transform": { "translation": [0, 3, 0] },
  "physics/RigidBody": { "kind": "dynamic" },
  "physics/Collider": { "shape": "cuboid", "halfExtents": [0.5, 0.5, 0.5], "restitution": 0.2 } } }
\`\`\`

- Kinds: \`dynamic\` (forces and contacts move it), \`fixed\`, \`kinematic-position\` (follows its
  Transform), \`kinematic-velocity\` (moves by \`physics/Velocity\`). A \`Collider\` without a body is fixed.
- Shapes: ball (\`radius\`), cuboid (\`halfExtents\`), capsule, cylinder, cone (\`radius\`, \`halfHeight\`
  along Y), convex and trimesh (\`mesh\`: a Mesh asset, or \`points\`), heightfield, segment, polyline.
  Scale in the Transform scales the shape. Colliders on children without their own body attach to
  the nearest ancestor body (one compound body).
- Move bodies with \`physics/Velocity\`, \`physics/ExternalForce\` (every step), or
  \`physics/ExternalImpulse\` (once). Writing a dynamic body's Transform teleports it.
- Layers: \`layers\` and \`mask\` are 16-bit masks; two colliders touch when each one's mask has the
  other's layer. Planets: \`physics/GravitySource\` on the planet, and \`physics/Config\` gravity \`[0, 0, 0]\`.
- Events: set \`events: true\` on a collider (sensors too) and read \`physics/CollisionEvent\`
  (\`started\` / \`stopped\`, the two collider entities and their bodies).
- Queries in code: \`world.resource(Physics).raycast(origin, dir, { mask }, hit)\`. From tools:
  \`physics_raycast\`, \`physics_overlap\`, \`physics_describe\`. See shapes with
  \`screenshot\` \`"overlays": ["colliders"]\`.

Check a fall with a gameplay test:

\`\`\`ts
test('the crate lands', async ({ game }) => {
  await game.load('scenes/main.scene.json')
  await game.step(120)
  expect(game.get('crate', 'core/Transform').translation[1]).toBeCloseTo(0.5, 1)
})
\`\`\`

## Characters

A walking player or NPC is \`physics/CharacterController\` with no RigidBody or Collider: it makes
its own kinematic capsule (centered on the entity), climbs steps and slopes, snaps to the ground,
pushes dynamic bodies, and rides kinematic platforms.

\`\`\`json
{ "name": "player", "components": {
  "core/Transform": { "translation": [0, 1, 0] },
  "physics/CharacterController": { "height": 1.8, "radius": 0.35, "up": "gravity" } } }
\`\`\`

- Write \`physics/CharacterIntent\`: \`move\` in m/s in the character's frame (x right, -z forward;
  2D: x), and \`jump: true\` to jump once at the next grounded step.
- Read \`physics/CharacterState\` (\`grounded\`, \`groundEntity\`, \`velocity\`, \`up\`, \`airTime\`) and
  \`physics/CharacterGroundEvent\` (landed or left the ground). \`physics_describe\` lists characters.
- \`up: "gravity"\` follows the strongest \`physics/GravitySource\` (walk around planets) and turns the
  entity to match; \`"fixed"\` uses \`fixedUp\` and \`gravity\`. Turn it by writing its rotation;
  writing its translation teleports it.

\`\`\`ts
test('the player walks and lands', async ({ game }) => {
  await game.load('scenes/main.scene.json')
  await game.step(30)
  await game.patch('player', { 'physics/CharacterIntent': { move: [0, 0, -3] } })
  await game.step(60)
  expect(game.get('player', 'physics/CharacterState').grounded).toBe(true)
  expect(game.get('player', 'core/Transform').translation[2]).toBeLessThan(-2.5)
})
\`\`\`
`,
  'make-a-data-asset.md': `# Make a data asset

Tuning data that isn't an entity (weapon stats, items, loot tables, wave schedules) is a project
data type: fields in \`scripts/\`, one JSON file per value.

1. **Define the type** with component-schema fields:

   \`\`\`ts
   export const Weapon = project.dataAsset('Weapon', {
     damage: t.f32({ default: 10, min: 0, unit: 'hp', description: 'Damage per hit.' }),
     fireRate: t.f32({ default: 4, unit: 'shots/s' }),
     projectile: t.handle('Prefab', { description: 'Spawned per shot.' }),
     upgradesTo: t.handle('<project>/Weapon'),
   }, { extension: 'weapon', description: 'A ship weapon.' })
   \`\`\`

   Run \`shard docs\`: the type shows up in \`.agents/assets.md\` and its schema is written to
   \`.shard/schemas/weapon.schema.json\`.
2. **Write files**: \`data/weapons/laser.weapon.json\`. Missing fields take their defaults.

   \`\`\`json
   { "$schema": "../../.shard/schemas/weapon.schema.json", "damage": 12,
     "projectile": { "path": "prefabs/bolt.prefab.json" } }
   \`\`\`
3. **Make a variant** that starts from another file and overrides fields (struct fields merge field
   by field, lists and handles replace):

   \`\`\`json
   { "$extends": { "path": "data/weapons/laser.weapon.json" }, "damage": 18 }
   \`\`\`

   Editing the base re-imports its variants. MCP \`get_asset\` on a variant shows its value, its
   \`extends\` chain, and which file set each field (\`info.setBy\`).
4. **Reference it** from a component: \`project.component('Armed', { weapon: t.handle('<project>/Weapon') })\`,
   and in a scene \`"<project>/Armed": { "weapon": { "path": "data/weapons/laser.weapon.json" } }\`.
   The weapon loads with the scene.
5. **Read it** in a system: \`world.resource(Weapon.store).get(armed.weapon)\` is one map lookup,
   no allocation. Every weapon at once: \`await loadAll(world, Weapon)\` (from \`@shard/assets\`).
6. **Check**: \`shard import --json\` then \`shard validate --json\`. Errors point into the file;
   a handle to the wrong type is \`schema/asset-type-mismatch\`, a loop of variants \`data/extends-cycle\`.

Saving a data file or changing the type's fields while the game runs reloads the values in place.
`,
  'make-a-prefab.md': `# Make a prefab

A prefab is a reusable entity tree: \`prefabs/<name>.prefab.json\`, validated against
\`.shard/schemas/prefab.schema.json\`. It has one \`root\` entity, written like a scene entity:

\`\`\`json
{ "$schema": "../.shard/schemas/prefab.schema.json", "version": 1,
  "assets": { "hull": { "type": "Material", "value": { "baseColor": "#8a93a6" } } },
  "root": { "name": "ship",
    "components": { "core/Transform": {}, "<project>/Health": { "max": 100 } },
    "children": [
      { "name": "Hull", "components": { "scene/SceneInstance": { "scene": { "path": "assets/ship.glb#Scene" } } } },
      { "name": "Exhaust", "components": { "particles/ParticleSystem": { "effect": { "path": "assets/fx/exhaust.particles.json" } } } }
    ] } }
\`\`\`

1. **Extract**: move an entity and its children out of a scene into \`root\`. Entity fields inside
   the prefab use paths from the root (\`"Hull"\`, \`"Hull/Cockpit"\`; \`"."\` is the root).
   \`shard import\` then \`shard validate --json\`: errors point into the file.
2. **Place** it in a scene. The instance entity *is* the root: the prefab's root components merge
   into it, and fields the entity sets win. Its children are generated, at \`player-ship/Exhaust\`:

   \`\`\`json
   { "name": "player-ship", "components": {
     "core/Transform": { "translation": [0, 5, 0] },
     "scene/PrefabInstance": { "prefab": { "path": "prefabs/ship.prefab.json" },
       "overrides": {
         "Exhaust": { "particles/ParticleSystem": { "timeScale": 2 } },
         "Hull/Cockpit": { "render/MeshMaterial": { "material": { "path": "materials/red.material.json" } } },
         "Hull/Antenna": null,
         "Exhaust/particles/ParticleEmitterOverrides": null } } } }
   \`\`\`

   Override keys are paths from the instance and reach into models inside it (\`Hull/Cockpit\`).
   A patch sets fields (adding the component if missing), \`null\` removes the entity, and a path
   ending in a component name set to \`null\` removes that component. Authored \`children\` of the
   instance sit next to the generated ones (names can't clash). \`scene/SceneInstance\` takes the same
   \`overrides\` for a model placed directly.
3. **Override live**: \`patch_entity\` on \`player-ship/Exhaust\`, check \`prefab_overrides\`, then
   \`save_scene\` with \`"write": true\`: the change is written into \`overrides\`, nothing else.
   \`prefab.apply\` (protocol) moves an instance's overrides into the prefab file instead.
4. **Variant**: a prefab that extends another. Editing the base updates every variant.

   \`\`\`json
   { "version": 1, "extends": { "path": "prefabs/ship.prefab.json" },
     "rootComponents": { "<project>/Health": { "max": 250 } },
     "overrides": { "Hull/Antenna": null },
     "children": [{ "name": "Turret", "components": { "core/Transform": {} } }] }
   \`\`\`
5. **Spawn from code**: load once, then spawning copies a compiled template (cheap enough for
   bullets). In a system, pass \`ctx.commands\` to spawn when the commands apply:

   \`\`\`ts
   import { loadPrefab, spawnPrefab } from '@shard/scene'
   await loadPrefab(world, 'prefabs/ship.prefab.json') // e.g. in the plugin's setup
   const ship = spawnPrefab(ctx.commands, 'prefabs/ship.prefab.json', {
     transform: { translation: [0, 5, 0] },
     overrides: { Exhaust: { 'particles/ParticleSystem': { timeScale: 2 } } },
   })
   \`\`\`

   Unloaded prefabs throw \`prefab/not-loaded\`. MCP \`spawn_prefab\` does the same from tools.

Saving a prefab file updates every running instance and keeps each one's overrides; an override
whose path no longer exists is kept in the file and logged as \`prefab/stale-override\`.
\`get_asset\` on a prefab shows its entity tree, and on a variant its base chain.
`,
  'make-particles.md': `# Make a particle effect

Add \`"particles"\` to \`plugins\` in \`shard.json\`. An effect is \`assets/fx/<name>.particles.json\`,
validated against \`.shard/schemas/particle-effect.schema.json\` (errors point into the file):

\`\`\`json
{ "emitters": [{ "name": "exhaust", "capacity": 20000, "spawn": { "rate": 4000 },
  "shape": { "type": "cone", "angle": 8, "radius": 0.2 },
  "init": { "lifetime": [0.3, 0.6], "speed": [18, 25], "size": [0.2, 0.35], "color": "#9ad4ff" },
  "update": [{ "module": "drag", "coefficient": 1.5 }, { "module": "curl-noise", "strength": 2 },
    { "module": "color-over-life", "gradient": [[0, "#e9f6ff", 1], [1, "#1a3a7a", 0]] }],
  "render": { "blend": "additive", "emissive": 4000 } }] }
\`\`\`

- Values: a number or \`[min, max]\`; curves \`[[t, v], …]\`; gradients \`[[t, color, alpha], …]\`.
- Modules: gravity, drag, velocity-over-life, curl-noise, attractor, rotation, color-over-life,
  size-over-life, collision (bounces off what the camera sees).
- Use it: \`"particles/ParticleSystem": { "effect": { "path": "assets/fx/exhaust.particles.json" } }\`;
  \`space: "local"\` keeps particles attached. Drive it from gameplay with
  \`particles/ParticleEmitterOverrides\` (\`spawnScale\`). Saving the file updates the running effect.
- Look: MCP \`preview_asset\` on the file shows it after one second; \`render.describe\` →
  \`particles\` gives alive counts.
`,
  'inspect-a-scene.md': `# Find what's wrong in a scene

When a screenshot looks wrong, connect the pixels to entities:

1. \`screenshot\` with \`"overlays": ["bounds", "labels"]\`: every mesh gets its outline and its scene
   path. Add \`"filter": "ship/"\` to label one subtree. Other overlays: lights, cameras, cascades,
   normals, axes.
2. \`pick\` a pixel that looks wrong (same coordinates as the screenshot): its path, position, and
   normal. Or \`raycast\` from a point, e.g. straight down to find the ground.
3. \`get_entity\` on that path, \`patch_entity\` the fix, and screenshot again with the same overlays.

In your own systems, draw with gizmos (they last one frame, or \`duration\` seconds):

\`\`\`ts
const g = world.resource(Gizmos)
g.line(from, to, [1, 0.2, 0.2, 1])
g.arrow(position, target, [1, 1, 0, 1], { width: 2 })
g.sphere(center, radius, [0, 1, 1, 1], { depthTest: false })
g.label(position, 'target', [1, 1, 1, 1])
\`\`\`

\`list_gizmos\` shows what was drawn as data. \`pick(world, camera, x, y)\` and
\`raycast(world, origin, direction)\` from \`@shard/render\` do the same in code.
`,
  'debug-with-screenshots.md': `# Look at the game

- \`shard screenshot <scene> --out shot.png --frames 60\` renders headless (no window needed).
- With the MCP server: \`screenshot\` returns the image; \`step\` advances frames; \`press\`/\`hold\`
  drive input; \`query_entities\` / \`get_entity\` read state; \`recent_errors\` shows what failed.
`,
}

function agentsBlock(manifest: ManifestValue): string {
  return `${GENERATED_START}
# ${manifest.name}

A [Shard](https://github.com/) project. The engine is data-first: scenes are JSON validated against
component schemas, game code is ECS (components, systems) in \`scripts/\`.

## Commands

\`\`\`sh
shard validate --json     # manifest, assets, scenes: every error with a path
shard import --json       # import new and changed asset files
shard mv <from> <to>      # move an asset and rewrite references to it
shard run --frames 600    # headless run
shard screenshot ${manifest.startScene} --out shot.png
shard test --json         # gameplay tests in tests/
shard check --json        # type-check scripts: file, line, column
shard dev                 # play it in a browser; saves hot reload in place
shard docs                # regenerate this block, .agents/, and .shard/schemas/
shard mcp                 # MCP server for this project (see .mcp.json)
\`\`\`

## Where things are

- \`shard.json\`: manifest (start scene: \`${manifest.startScene}\`, seed ${manifest.seed}, plugins: ${manifest.plugins.join(', ')})
- \`scripts/main.ts\`: the project plugin; project types are named \`${manifest.name}/<Name>\`
- \`scenes/\`: scene files; \`tests/\`: gameplay tests; \`shaders/\`: \`project::\` shader modules
- \`${manifest.assetRoots.join('/`, `')}/\`: asset files, each with a \`.meta\` (guid, import settings)
- \`.agents/components.md\`: every component and field; \`.agents/assets.md\`: importers and
  project data types;
  \`.agents/errors.md\`: error codes
- \`.agents/skills/\`: recipes for common tasks

Engine plugins available: ${Object.entries(BUILTIN_PLUGINS)
    .map(([n, d]) => `\`${n}\` (${d})`)
    .join('; ')}.
${GENERATED_END}`
}

/** Replaces the generated block in AGENTS.md, keeping everything outside the markers. */
export function mergeAgentsMd(existing: string | undefined, manifest: ManifestValue): string {
  const block = agentsBlock(manifest)
  if (!existing)
    return `${block}\n\n## Notes\n\nProject-specific notes for agents go here; \`shard docs\` keeps them.\n`
  const start = existing.indexOf(GENERATED_START)
  const end = existing.indexOf(GENERATED_END)
  if (start === -1 || end === -1) return `${block}\n\n${existing}`
  return `${existing.slice(0, start)}${block}${existing.slice(end + GENERATED_END.length)}`
}

/** Every generated file except AGENTS.md (see `mergeAgentsMd`), by project-relative path. */
export function generateDocs(
  manifest: ManifestValue,
  errors: readonly ErrorCode[],
): Record<string, string> {
  const files: Record<string, string> = {
    '.agents/components.md': renderComponentCatalog(),
    '.agents/errors.md': renderErrorCatalog(errors),
    '.agents/assets.md': renderAssetCatalog(
      allImporters(),
      allDataTypes().filter((d) => d.name.startsWith(`${manifest.name}/`)),
    ),
    '.shard/schemas/shard.schema.json': `${JSON.stringify(manifestJsonSchema(), null, 2)}\n`,
    '.shard/schemas/scene.schema.json': `${JSON.stringify(sceneJsonSchema(), null, 2)}\n`,
    '.shard/schemas/prefab.schema.json': `${JSON.stringify(prefabJsonSchema(), null, 2)}\n`,
  }
  for (const [name, content] of Object.entries(SKILLS))
    files[`.agents/skills/${name}`] = content.replaceAll('<project>', manifest.name)
  for (const [file, schema] of allAssetSchemas()) {
    files[`.shard/schemas/${file}`] = `${JSON.stringify(schema(), null, 2)}\n`
  }
  for (const def of allComponents()) {
    if (def.name.startsWith('test/')) continue
    files[`.shard/schemas/components/${def.name.replace('/', '.')}.json`] =
      `${JSON.stringify(def.jsonSchema(), null, 2)}\n`
  }
  return files
}
