import { allComponents, type ComponentDef, type JsonSchema } from '@shard/core'
import { sceneJsonSchema } from '@shard/scene'
import { BUILTIN_PLUGINS, type ManifestValue, manifestJsonSchema } from './manifest'

export const GENERATED_START = '<!-- shard:generated -->'
export const GENERATED_END = '<!-- /shard:generated -->'

export interface ErrorCode {
  code: string
  hint?: string
  /** Package or file it comes from. */
  source: string
}

function fieldRow(name: string, schema: JsonSchema): string {
  const type = describeType(schema)
  const def = schema.default === undefined ? '' : `\`${JSON.stringify(schema.default)}\``
  const range = [
    schema.minimum !== undefined ? `≥ ${schema.minimum}` : '',
    schema.maximum !== undefined ? `≤ ${schema.maximum}` : '',
    schema['x-unit'] ? `${schema['x-unit']}` : '',
  ]
    .filter(Boolean)
    .join(', ')
  const presets = schema['x-presets']
    ? ` Presets: ${Object.keys(schema['x-presets'] as object).join(', ')}.`
    : ''
  const description = `${(schema.description as string | undefined) ?? ''}${presets}`.replace(
    /\|/g,
    '\\|',
  )
  return `| \`${name}\` | ${type} | ${def} | ${range} | ${description} |`
}

function describeType(schema: JsonSchema): string {
  if (schema.anyOf) return (schema.anyOf as JsonSchema[]).map(describeType).join(' or ')
  if (schema.enum) return (schema.enum as string[]).map((v) => `\`"${v}"\``).join(' \\| ')
  if (schema.type === 'array') {
    const n =
      schema.minItems === schema.maxItems && schema.minItems !== undefined
        ? `${schema.minItems}`
        : ''
    return `${describeType((schema.items as JsonSchema) ?? {})}[${n}]`
  }
  if (schema.type === 'object' && schema.properties && (schema.properties as JsonSchema).guid)
    return 'asset ref'
  return (schema.type as string | undefined) ?? 'any'
}

/** A readable catalog of components: the same facts as the JSON Schemas, for agents to skim. */
export function renderComponentCatalog(defs: readonly ComponentDef[] = allComponents()): string {
  const visible = defs.filter((d) => !d.name.startsWith('test/'))
  const lines = [
    '# Components',
    '',
    'Generated by `shard docs` from the registry. Use these names as keys under `components` in scene files.',
    '',
  ]
  for (const def of visible) {
    lines.push(`## \`${def.name}\``, '')
    if (def.description) lines.push(def.description, '')
    if (!def.serializable) lines.push('_Computed by the engine; never written in scene files._', '')
    if (def.requires.length > 0)
      lines.push(`Brings along: ${def.requires.map((r) => `\`${r.name}\``).join(', ')}.`, '')
    const props = (def.jsonSchema().properties ?? {}) as Record<string, JsonSchema>
    if (Object.keys(props).length === 0) {
      lines.push('Tag (no fields).', '')
      continue
    }
    lines.push('| Field | Type | Default | Range | Description |', '|---|---|---|---|---|')
    for (const [name, schema] of Object.entries(props)) lines.push(fieldRow(name, schema))
    if (def.name === 'core/Transform') {
      lines.push(
        '| `rotationEuler` | number[3] | | degrees | Scene files only: rotation as X, then Y, then Z degrees. |',
      )
    }
    lines.push('')
  }
  return lines.join('\n')
}

export function renderErrorCatalog(codes: readonly ErrorCode[]): string {
  const lines = [
    '# Error codes',
    '',
    'Every engine error is a `ShardError` with one of these codes.',
    '',
  ]
  lines.push('| Code | Source | Hint |', '|---|---|---|')
  for (const c of [...codes].sort((a, b) => a.code.localeCompare(b.code))) {
    lines.push(`| \`${c.code}\` | ${c.source} | ${(c.hint ?? '').replace(/\|/g, '\\|')} |`)
  }
  return `${lines.join('\n')}\n`
}

const SKILLS: Record<string, string> = {
  'build-a-scene.md': `# Build or change a scene

1. Read \`.agents/components.md\` for component names and fields.
2. Edit \`scenes/*.scene.json\`. Name every entity; nest with \`children\`. Materials go in \`assets\`
   (\`{ "type": "Material", "value": {...} }\`), meshes can be procedural
   (\`{ "path": "procedural:sphere?radius=2" }\`).
3. Validate: \`shard validate --json\` (or the MCP \`validate_scene\` tool). Fix every error by its \`path\`.
4. Look at it: \`shard screenshot scenes/main.scene.json --out shot.png\` (or MCP \`screenshot\`).
`,
  'add-a-component.md': `# Add a component

In \`scripts/\`, define it on the project so it gets the project namespace:

\`\`\`ts
export const Fuel = project.component('Fuel', {
  liters: t.f32({ default: 100, min: 0, unit: 'L', description: 'Fuel left.' }),
})
\`\`\`

Write a description for every field: it ends up in \`.agents/components.md\`. Run \`shard docs\` after.
`,
  'write-a-system.md': `# Write a system

\`\`\`ts
const burn = defineSystem({
  name: '<project>/burn',
  setup: (world) => ({ q: world.query({ with: [Fuel] }) }),
  run: ({ q }, world) => {
    const dt = world.resource(FixedTime).step
    for (const table of q.tables) {
      const liters = table.column(Fuel, 'liters')
      for (let i = 0; i < table.count; i++) liters[i] = Math.max(0, liters[i]! - dt)
      table.markChanged(Fuel)
    }
  },
})
\`\`\`

Register it in the project's \`build(app)\`: \`app.addSystems(FixedUpdate, burn)\`. Hot loops must not
allocate: walk \`q.tables\` and use columns.
`,
  'write-a-gameplay-test.md': `# Write a gameplay test

\`\`\`ts
import { expect, test } from '@shard/testing'

test('thrust moves the ship', async ({ game }) => {
  await game.load('scenes/main.scene.json')
  game.input.hold('<project>/Controls.thrust')
  await game.step(120)
  expect(game.get('ship', 'core/Transform').translation[2]).toBeLessThan(0)
})
\`\`\`

Run with \`shard test --json\`. Tests are headless, seeded, and fixed-timestep: they pass or fail the
same way every run.
`,
  'debug-with-screenshots.md': `# Look at the game

- \`shard screenshot <scene> --out shot.png --frames 60\` renders headless (no window needed).
- With the MCP server: \`screenshot\` returns the image; \`step\` advances frames; \`press\`/\`hold\`
  drive input; \`query_entities\` / \`get_entity\` read state; \`recent_errors\` shows what failed.
`,
}

function agentsBlock(manifest: ManifestValue): string {
  return `${GENERATED_START}
# ${manifest.name}

A [Shard](https://github.com/) project. The engine is data-first: scenes are JSON validated against
component schemas, game code is ECS (components, systems) in \`scripts/\`.

## Commands

\`\`\`sh
shard validate --json     # manifest, scenes, schemas: every error with a path
shard run --frames 600    # headless run
shard screenshot ${manifest.startScene} --out shot.png
shard test --json         # gameplay tests in tests/
shard docs                # regenerate this block, .agents/, and .shard/schemas/
shard mcp                 # MCP server for this project (see .mcp.json)
\`\`\`

## Where things are

- \`shard.json\`: manifest (start scene: \`${manifest.startScene}\`, seed ${manifest.seed}, plugins: ${manifest.plugins.join(', ')})
- \`scripts/main.ts\`: the project plugin; project types are named \`${manifest.name}/<Name>\`
- \`scenes/\`: scene files; \`tests/\`: gameplay tests; \`shaders/\`: \`project::\` shader modules
- \`.agents/components.md\`: every component and field; \`.agents/errors.md\`: error codes
- \`.agents/skills/\`: recipes for common tasks

Engine plugins available: ${Object.entries(BUILTIN_PLUGINS)
    .map(([n, d]) => `\`${n}\` (${d})`)
    .join('; ')}.
${GENERATED_END}`
}

/** Replaces the generated block in AGENTS.md, keeping everything outside the markers. */
export function mergeAgentsMd(existing: string | undefined, manifest: ManifestValue): string {
  const block = agentsBlock(manifest)
  if (!existing)
    return `${block}\n\n## Notes\n\nProject-specific notes for agents go here; \`shard docs\` keeps them.\n`
  const start = existing.indexOf(GENERATED_START)
  const end = existing.indexOf(GENERATED_END)
  if (start === -1 || end === -1) return `${block}\n\n${existing}`
  return `${existing.slice(0, start)}${block}${existing.slice(end + GENERATED_END.length)}`
}

/** Every generated file except AGENTS.md (see `mergeAgentsMd`), by project-relative path. */
export function generateDocs(
  manifest: ManifestValue,
  errors: readonly ErrorCode[],
): Record<string, string> {
  const files: Record<string, string> = {
    '.agents/components.md': renderComponentCatalog(),
    '.agents/errors.md': renderErrorCatalog(errors),
    '.shard/schemas/shard.schema.json': `${JSON.stringify(manifestJsonSchema(), null, 2)}\n`,
    '.shard/schemas/scene.schema.json': `${JSON.stringify(sceneJsonSchema(), null, 2)}\n`,
  }
  for (const [name, content] of Object.entries(SKILLS))
    files[`.agents/skills/${name}`] = content.replaceAll('<project>', manifest.name)
  for (const def of allComponents()) {
    if (def.name.startsWith('test/')) continue
    files[`.shard/schemas/components/${def.name.replace('/', '.')}.json`] =
      `${JSON.stringify(def.jsonSchema(), null, 2)}\n`
  }
  return files
}
