export {
  InstancePart,
  PrefabAssets,
  PrefabAssetType,
  PrefabInstance,
  SceneAssets,
  SceneAssetType,
  SceneIndex,
  SceneInstance,
  SceneMember,
} from './components'
export {
  type Overrides,
  PREFAB_VERSION,
  type PrefabFile,
  SCENE_VERSION,
  type SceneAsset,
  type SceneEntity,
  type SceneFile,
} from './format'
export {
  currentOverrides,
  defineInstanceKind,
  hookInstances,
  type InstanceKind,
  instanceEntities,
  instanceKindOf,
  instanceKinds,
  instanceOf,
  loadInstanceAssets,
  loadPrefab,
  mergeOverridesIntoPrefab,
  prefabOfInstance,
  prefabRootComponents,
  releaseSceneHooks,
  ScenePlugin,
  type SpawnPrefabOptions,
  sceneInstancesSystem,
  settleInstances,
  spawnPrefab,
  updateInstances,
} from './instances'
export {
  applyToPrefab,
  applyVariant,
  type PrefabFiles,
  PrefabImporter,
  registeredPrefab,
  registerPrefab,
  validatePrefab,
} from './prefab-file'
export {
  defineProceduralSource,
  PROCEDURAL_MESHES,
  type ProceduralRef,
  type ProceduralSource,
  parseProcedural,
  proceduralSourceFor,
} from './procedural'
export {
  addSceneReadyCheck,
  expandComponentAliases,
  findEntityByPath,
  type LoadedSceneHandle,
  loadScene,
  pathOfEntity,
  reloadScene,
  saveScene,
  stringifyScene,
  unloadScene,
  validateScene,
  whenSceneReady,
  worldSchemaContext,
} from './scene'
export { prefabJsonSchema, sceneJsonSchema } from './schema'
