/** The playground's demos, in the order the page lists them. `location.hash` picks one. */
export const DEMOS = [
  'scene',
  'galaxy',
  'lights',
  'ibl',
  'sky',
  'deferred',
  'crowd',
  'post',
  'lens',
  'sprites',
  'particles',
  'physics',
  'planet',
  'physics2d',
  'character',
  'character-planet',
  'character2d',
  'prefabs',
  'data',
  'animation',
  'animgraph',
  'ik',
  'audio',
  'ui',
  'nav',
  'nav2d',
  'save',
  'lights2d',
  'grids',
  'noise',
  'procgen',
  'terrain',
  'atmosphere',
  'tabletop',
] as const

export type Demo = (typeof DEMOS)[number]
